# fly.toml app configuration file generated for nginx-rtmp on 2025-07-25T18:35:29-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nginx-rtmp'
primary_region = 'iad'

[build]

# HTTP service for HLS (.m3u8, .ts files)
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

# RTMP service for ingest (OBS, mobile apps)
[[services]]
  internal_port = 1935
  protocol = "tcp"

  [[services.ports]]
    port = 1935

# HLS service explicitly mapped (optional, for clarity — already covered by http_service)
[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[mounts]
  source = "hls_data"
  destination = "/mnt/hls"

# VM resources
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
